project_id = "ukznsekygmipnucpouoy"

[functions.summarize]
verify_jwt = false

[functions.qa]
verify_jwt = false

[functions.qa-stream]
verify_jwt = false

[functions.summarize-stream]
verify_jwt = false

[functions.save-page-summary]
verify_jwt = false

[functions.admin-add-book]
verify_jwt = false

[functions.ocr-gemini]
verify_jwt = false

[functions.ocr-deepseek]
verify_jwt = false

[functions.process-complete-book]
verify_jwt = false

[functions.ocr-fallback]
verify_jwt = false

[functions.image-proxy]
verify_jwt = false

[functions.generate-suggestions]
verify_jwt = false

[functions.backfill-embeddings]
verify_jwt = false

[functions.generate-embedding]
verify_jwt = false

[functions.get-rag-context]
verify_jwt = false
