project_id = "ukznsekygmipnucpouoy"

[functions.summarize]
verify_jwt = false

[functions.qa]
verify_jwt = false

[functions.qa-stream]
verify_jwt = false

[functions.summarize-stream]
verify_jwt = false

[functions.save-page-summary]
verify_jwt = false

[functions.ocr-gemini]
verify_jwt = false

[functions.ocr-deepseek]
verify_jwt = false
